language: c
compiler: gcc
dist: trusty

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    skip_cleanup: true
    acl: public_read
    bucket: $MODULE_NAME.io
    on:
      branch: master
    local_dir: $TRAVIS_BUILD_DIR